# Deployment - Runs the Homepage application
# - What it is: Manages Homepage pods
# - Comparison to Docker: Similar to "services.homepage" in docker-compose.yaml
# - Behavior: Ensures 1 replica of Homepage is always running
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glances
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glances
  template:
    metadata:
      labels:
        app: glances
    spec:
      containers:
        - name: glances
          image: nicolargo/glances:4.4.1
          ports:
            - name: http
              containerPort: 61208
          env:
            - name: GLANCES_OPT
              value: "-w"
          volumeMounts:
            - name: config
              mountPath: /glances
      volumes:
        - name: config
          configMap:
            name: glances-config
