apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: glances
  namespace: homelab
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: homelab
      sectionName: http
  hostnames:
    - "glances-dev.gaborzeller.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: glances
          port: 61208

