entryPoints:
  web:
    address: ":80"

api:
  dashboard: true
  insecure: true # using cloudflare tunnel, hence why not handling TLS certs with traefik just internal routing
  basepath: "/traefik/"

providers:
  docker:
    # endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # only want to discover containers that I am explicitly labeling
    useBindPortIP: false # Don't want to expose IP/Port to the host everything should happen inside docker's internal network
    # httpClientTimeout: "10" # do time out in 10 seconds
    watch: true # watch for docker events and update
    # tls:
    #   insecureSkipVerify: true 

log:
  level: "INFO"
