# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- System:
    - Traefik:
        icon: traefik.png
        href: /traefik/dashboard/
        description: Internal routing
        statusStyle: "dot"
        ping: traefik
        widget:
          type: traefik
          url: http://traefik/traefik

    - Netdata:
        icon: netdata.png
        href: /netdata
        description: Systems monitoring
        statusStyle: "dot"
        ping: netdata
        widget:
          type: netdata
          url: http://netdata:19999

- Work:
    - Nginx:
        icon: alexa.png
        href: /nginx
        description: To nginx
        statusStyle: "dot"
        ping: nginx

- Personal:
    - Nginx:
        icon: alexa.png
        href: /nginx
        description: To nginx
        statusStyle: "dot"
        ping: nginx

