# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- DigitalOcean:
    - Nginx:
        icon: alexa.png
        href: /nginx
        description: To nginx
        statusStyle: "dot"
        ping: nginx

- Core:
    - Traefik:
        icon: traefik.png
        href: /traefik/dashboard/
        description: Internal routing
        statusStyle: "dot"
        ping: traefik
        widget:
          type: traefik
          url: http://traefik/traefik
