apiVersion: v1
data:
  bookmarks.yaml: |
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/bookmarks

    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/

    - Social:
        - Reddit:
            - abbr: RE
              href: https://reddit.com/

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
  kubernetes.yaml: |
    mode: cluster
    # https://gethomepage.dev/configs/kubernetes/#traefik-ingressroute-support
    gateway: true # enable gateway-api
  services.yaml: |
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/services/

    - System:
        - Traefik:
            icon: traefik.png
            href: https://traefik-dev.gaborzeller.com
            namespace: homelab
            description: Reverse proxy
            statusStyle: "dot"
            ping: reverse-proxy
            # ping: http://reverse-proxy:8080/api/overview
            # widget:
            #   type: traefik
            #   url: https://traefik-dev.gaborzeller.com

      # - Netdata:
      #     icon: netdata.png
      #     href: /netdata
      #     description: Systems monitoring
      #     statusStyle: "dot"
      #     ping: netdata
      #     widget:
      #       type: netdata
      #       url: http://netdata:19999

      # - Glances:
      #     icon: glances.png
      #     href: /glances
      #     description: System monitoring
      #     statusStyle: "dot"
      #     ping: glances
      #
      # - System:
      #     href: /glances
      #     widget:
      #       type: glances
      #       url: http://glances:61208/glances
      #       version: 4 # required only if running glances v4 or higher, defaults to 3
      #       metric: info
      #       # chart: false
      #
      # - Containers:
      #     href: /glances
      #     widget:
      #       type: glances
      #       url: http://glances:61208/glances
      #       version: 4 # required only if running glances v4 or higher, defaults to 3
      #       metric: containers
      #       # chart: false


    # - Work:
    #     - Nginx:
    #         icon: alexa.png
    #         href: /nginx
    #         description: To nginx
    #         statusStyle: "dot"
    #         ping: nginx
    #
    # - Personal:
    #     - Nginx:
    #         icon: alexa.png
    #         href: /nginx
    #         description: To nginx
    #         statusStyle: "dot"
    #         ping: nginx
    #
  settings.yaml: |
    title: My Awesome Homepage
    description: A description of my awesome homepage
  widgets.yaml: |+
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default

    - search:
        provider: duckduckgo
        target: _blank

kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homelab
