# docker run --rm -v ollama-models:/root/.ollama --gpus=all -p 11434:11434 --name ollama ollama/ollama:0.15.1
services:
  ollama:
    image: ollama/ollama:0.15.1
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    # https://docs.docker.com/compose/how-tos/gpu-support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  glances:
    image: nicolargo/glances:ubuntu-4.4.1-full
    container_name: glances
    pid: host
    network_mode: host
    # ports:
    #   - "61208:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # https://docs.docker.com/compose/how-tos/gpu-support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - "GLANCES_OPT=-w"
    restart: unless-stopped


volumes:
  ollama-models:
    external: true
  netdataconfig:
    external: true
  netdatalib:
    external: true
  netdatacache:
    external: true



